# Generated by Django 5.1.3 on 2024-11-17 19:14

import timezone_field.fields
import utils.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_time_zone_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=utils.common.models.BaseModel.get_file_path, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(verbose_name='time zone'),
        ),
    ]
