# Generated by Django 5.1.3 on 2024-11-21 19:08

import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='UTC', verbose_name='time zone'),
        ),
    ]
